apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-schemas
  labels:
    app: {{ .Release.Name }}
data:
  {{- range $path, $_ := .Files.Glob "schemas/aws/*.json" }}
  {{ base $path }}: |-
    {{ $.Files.Get $path | nindent 4 }}
  {{- end }}
