apiVersion: v1
kind: Service
metadata:
  name: {{ include "wolkvorm.fullname" . }}-backend
  labels:
    {{- include "wolkvorm.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wolkvorm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wolkvorm.fullname" . }}-frontend
  labels:
    {{- include "wolkvorm.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wolkvorm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
